### ISSUE TITLE
Do not generate bindings for functions implemented in the header

### ISSUE THREAD

**Issue by armanbilge** [indoorvivants/sn-bindgen#120]
https://github.com/axboe/liburing/blob/0535620c15e1133f9c19aefe9e928e0607e6c2b2/src/include/liburing.h#L283-L309

They will compile but graduate to linking errors.

**Comment by armanbilge** [comment]
Yes I did, you can see in https://github.com/armanbilge/fs2-io_uring/pull/2.

**Comment by keynmol** [comment]
Hmm, so should this be considered internal API then? 
Can you achieve what you need without using that function?

Because as it stands it's sort of at compiler's mercy to include/not include it.

If you got a linking error, that means the shared library for io_uring doesn't have an entry for this function - which must mean you're supposed to use some other means of achieving the same effect?

**Comment by keynmol** [comment]
What I'm trying to get at is that `inline` functions are weird:

```
$ cat test.c
#include "test.h"

$ cat test.h
static inline int test_inline(int c) {
  return c + 5;
}

extern int text_regular(int c) {
  return c + 11;
}
```

If we just compile that, you can see that the inline function is elided:

```
$ clang -c test.h test.c

$ nm ./test.o
0000000000000000 T _text_regular
0000000000000000 t ltmp0
0000000000000018 s ltmp1
```

And even though `text_regular` is defined in the header, it's available in the binary artifact.

Now, if you _use_ the inline function in the source that produces your binary artifact (liburing.dylib, for exaple), then inline function can be added there:

```

$ cat test1.c
#include "test.h"

void help() {
  test_inline(25);
}

$ clang -c test.h test1.c

$ nm test1.o
0000000000000018 T _help
0000000000000030 t _test_inline
0000000000000000 T _text_regular
0000000000000000 t ltmp0
0000000000000048 s ltmp1
``` 

What I'm saying is that

1. The issue needs to be changed to clarify that we shouldn't "generate bindings for **inline functions**" - header or not, I think, is not an issue
2. in a more general sense, I don't understand how the function can be part of public binary API if it may or may not be inlined depending on compiler settings..

**Comment by keynmol** [comment]
Now, bindgen could generate a glue C function for an inlined one, thus ensuring that the compiler will add the inline function to list of symbols in the resulting object artifacts

**Comment by keynmol** [comment]
Yes, if you accompany a binary liburing artifact with your own sources that exercise these inlined functions, then they should either be preserved, or fully inlined - and this means that the C functions you write shouldn't notice either way.

That's my understanding at least - which means that bindgen can generate Scala functions that invoke wrappers that invoke inline functions...

**Comment by armanbilge** [comment]
> Yes, if you accompany a binary liburing artifact with your own sources that exercise these inlined functions, then they should either be preserved, or fully inlined - and this means that the C functions you write shouldn't notice either way.

Right, I wasn't aware there was another way to use these functions 😛

**Comment by keynmol** [comment]
I've created #121 to track this particular improvement. 
You can do as you wish with this issue :P

**Comment by armanbilge** [comment]
- https://github.com/indoorvivants/sn-bindgen/issues/121
