### ISSUE TITLE
libclang-17.so.17: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by faveoled** [indoorvivants/sn-bindgen#280]
```
2024.03.07 21:16:23 ERROR /home/user/.cache/coursier/v1/https/repo1.maven.org/maven2/com/indoorvivants/bindgen_native0.4_3/0.1.2/bindgen_native0.4_3-0.1.2-x86_64-linux.jar: error while loading shared libraries: libclang-17.so.17: cannot open shared object file: No such file or directory
```
Got this error when trying to compile bindings. I'm on Ubuntu 22.04. Any ideas?

**Comment by keynmol** [comment]
Starting from bindgen 0.1.0 it's linked against LLVM 17 (my hand was sort of forced by unrelated CI changes) - I updated the instructions on the Quick start page: https://sn-bindgen.indoorvivants.com/quickstart/index.html#pre-requisites

Or are you seeing this error with LLVM 17 installed?

**Comment by faveoled** [comment]
No, the older one

**Comment by keynmol** [comment]
Let me know if installing LLVM 17 fixes the issue.

**Comment by keynmol** [comment]
Installing LLVM 17 should fix this, so closing the issue.
If not, please reopen the issue
