### ISSUE TITLE
Integrate with vcpkg 

### ISSUE THREAD

**Issue by keynmol** [indoorvivants/sn-bindgen#73]
Vcpkg seems like absolute magic. 

To take this project to the next level of usability, I propose two new settings:

```scala
bindgenEnableVCPKG := true,
bindgenVCPKGDependencies := Map("czmq" -> "1.0", "libuv" -> "1.43")
```

(names pending)

If VCPKG is enabled, the following process happens under the hood:

1. SBT plugin bootstraps vcpkg in some local folder
2. Dependencies are installed into the target folder
3. Header files for those dependencies are passed into the binding generator
4. Library files for those libraries are added to the linking config

In the end, the user just lists their dependencies like they would with something like ScalablyTyped, but with the added benefit that they can directly build statically linked binaries

**Comment by armanbilge** [comment]
Serializing some Discord discussion.

> I feel like there's two parts to that. isn't that useful also for downstream libs/apps that don't need bindings, but do need the deps. the other interesting bit is communicating transitive deps

> For sure. 
> That plugin can be separate and then the sn-bindgen one can build on top of that
> At this point I'd be happy to build anything
> It'd be quite exciting if it works out - vcpkg registry is quite big, and the experience will be even better than ScalablyTyped, because you don't need a separate bundler - everything will be linked

If there's no rush, I might give this a try sometime :)

**Comment by armanbilge** [comment]
For example, this would be helpful for propagating the [utf8proc](https://juliastrings.github.io/utf8proc/) dependency from [scala-java-locales](https://github.com/cquiroz/scala-java-locales) -> [saslprep](https://github.com/armanbilge/saslprep/) -> someday skunk.

**Comment by armanbilge** [comment]
👍 that might be helpful to better understand the needs/constraints.

**Comment by keynmol** [comment]
I fell on my own nerd grenade and created a shoddy plugin: https://github.com/indoorvivants/sbt-vcpkg
It's currently published to Maven Central and used successfully along with binding generator here: https://github.com/keynmol/sn-bindgen-examples/pull/26

**Comment by keynmol** [comment]
Due to the unpredictable structure of the `include` folder of each installed dependency, and the fact that sn-vcpkg now has a lot of features, I will close this.

> Header files for those dependencies are passed into the binding generator

This is the only requirement that isn't satisfied and frankly I don't believe it ever will be, given the assorted ways in which header files are shipped.
